{
 "title": "banking_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Blacklisted account transactions",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "select account_id, count(*) as blacklisted_accounts from banking_data where account_blacklisted = true group by account_id"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT COUNT(*) FROM banking_data WHERE decision = 'Rejected';"
    }
   ]
  },
  {
   "title": "Approved",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT COUNT(*) FROM banking_data WHERE decision = 'Approved';"
    }
   ]
  },
  {
   "title": "Authorization",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT trans_type, COUNT(*) FROM banking_data GROUP BY trans_type LIMIT 50"
    }
   ]
  }
 ]
}